version: '2'
services:
  db:
    build: ./db
    ports:
    - "8080:8080"
    - "28015:28015"
  warcprox:
    build: ./warcprox
    volumes:
    - "/warcs:/warcs"
    ports:
    - "8000:8000"
  worker:
    build: ./worker 
    environment:
    - BROZZLER_RETHINKDB_SERVERS=db
    - BROZZLER_RETHINKDB_DB=brozzler
    ports:
    - "127.0.0.1:5900:5900"
  pywb:
    build: ./pywb
    volumes:
    - "/warcs:/warcs"
    ports:
    - "8880:8880"
  dashboard:
    build: ./dashboard
    environment:
    - BROZZLER_RETHINKDB_SERVERS=db
    - BROZZLER_RETHINKDB_DB=brozzler
    - WAYBACK_BASEURL=http://brozzler:8880/brozzler
    ports:
    - "8881:8881"
